alpha: 0.1
discriminator_save_dir: false
dloss_function: ''
dr: 0.9
final_dir: final
init_method: mean
init_num: 1
intermediate_dir: ''
lr: 0.1
model: 30_classes_model
model_path: false
n_iters: 10
noise_std: 0.5
num_classes: false
resolution: 128
seed_z: 0
steps_per_z: 20
target_class: 2
today_date: noise_std
today_time: 0.5
use_noise_layer: false
z_num: 10
